name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  direct_link:
    path: ../
  cached_network_image: ^3.3.1
  file_picker: ^8.0.6
  go_router: ^14.2.1

dev_dependencies:
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0
  go_router_builder: ^2.7.0

flutter:
  uses-material-design: true
