name: direct_link
description: Direct link extractor from URL to stream and download directly.
version: 0.2.3
repository: https://github.com/thitlwincoder/direct_link
issue_tracker: https://github.com/thitlwincoder/direct_link/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  web:
  linux:
  macos:
  windows:

funding:
  - https://paypal.me/thitlwin312
  - https://ko-fi.com/thitlwincoder

dependencies:
  flutter:
    sdk: flutter

  html: ^0.15.4
  puppeteer: ^3.12.0
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
